#!/usr/bin/env bash

if [ -n "$WWWUSER" ]; then
  usermod -u "$WWWUSER" sail
fi

if [ ! -d /.composer ]; then
  mkdir /.composer
fi

chmod -R ugo+rw /.composer

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
